version: '3.8'

services:
  autoflux:
    build: .
    image: gamedata-autoflux:latest
    container_name: autoflux_app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
