"""baseline records scheduler_states agent_sessions

初始 schema：records / scheduler_states / agent_sessions 三表与其索引，
等价于历史 create_all + 手写 ALTER 的最终形态。
存量 create_all 库由启动逻辑 stamp 到本 revision，无需手工处理。

Revision ID: 86215de297eb
Revises:
Create Date: 2026-08-22 22:27:30.657833

"""
from __future__ import annotations

from typing import Sequence, Union

import pgvector.sqlalchemy.vector
from alembic import op
import sqlalchemy as sa

import src.storage.models


# revision identifiers, used by Alembic.
revision: str = '86215de297eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _try_enable_vector(conn) -> bool:
    """尽力启用 pgvector 扩展；服务器未安装时返回 False，embedding 降级 JSONB。

    与 src.storage.models 的 VectorType 回退语义保持一致：
    无 vector 的部署仍可启动，只是语义检索不可用。
    注意必须用 SAVEPOINT（begin_nested）——直接 rollback 会把
    Alembic 的外层迁移事务一起回滚掉。
    """
    from sqlalchemy import text

    try:
        with conn.begin_nested():
            conn.execute(text("CREATE EXTENSION IF NOT EXISTS vector"))
        return True
    except Exception:
        return False


def upgrade() -> None:
    conn = op.get_bind()
    has_vector = _try_enable_vector(conn)
    embedding_type = (
        pgvector.sqlalchemy.vector.VECTOR(dim=1536) if has_vector else src.storage.models.JSONType()
    )
    op.create_table('agent_sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('messages', src.storage.models.JSONType(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('records',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('collector', sa.String(), nullable=True),
    sa.Column('game_name', sa.String(), nullable=True),
    sa.Column('app_id', sa.String(), nullable=True),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('metadata', src.storage.models.JSONType(), nullable=True),
    sa.Column('tags', src.storage.models.JSONType(), nullable=True),
    sa.Column('data', src.storage.models.JSONType(), nullable=True),
    sa.Column('embedding', embedding_type, nullable=True),
    sa.Column('stored_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_records_app_id'), 'records', ['app_id'], unique=False)
    op.create_index(op.f('ix_records_collector'), 'records', ['collector'], unique=False)
    op.create_index(op.f('ix_records_game_name'), 'records', ['game_name'], unique=False)
    op.create_index(op.f('ix_records_source'), 'records', ['source'], unique=False)
    op.create_index(op.f('ix_records_stored_at'), 'records', ['stored_at'], unique=False)
    op.create_table('scheduler_states',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('state_type', sa.String(), nullable=False),
    sa.Column('data', src.storage.models.JSONType(), nullable=True),
    sa.Column('metadata', src.storage.models.JSONType(), nullable=True),
    sa.Column('task_status', sa.String(), nullable=True),
    sa.Column('stored_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_scheduler_states_state_type'), 'scheduler_states', ['state_type'], unique=False)
    op.create_index(op.f('ix_scheduler_states_stored_at'), 'scheduler_states', ['stored_at'], unique=False)
    op.create_index(op.f('ix_scheduler_states_task_status'), 'scheduler_states', ['task_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduler_states_task_status'), table_name='scheduler_states')
    op.drop_index(op.f('ix_scheduler_states_stored_at'), table_name='scheduler_states')
    op.drop_index(op.f('ix_scheduler_states_state_type'), table_name='scheduler_states')
    op.drop_table('scheduler_states')
    op.drop_index(op.f('ix_records_stored_at'), table_name='records')
    op.drop_index(op.f('ix_records_source'), table_name='records')
    op.drop_index(op.f('ix_records_game_name'), table_name='records')
    op.drop_index(op.f('ix_records_collector'), table_name='records')
    op.drop_index(op.f('ix_records_app_id'), table_name='records')
    op.drop_table('records')
    op.drop_table('agent_sessions')
    # ### end Alembic commands ###
